FROM python:3.11-bookworm

RUN apt update && apt install -y fontconfig python3-venv python3-pip git poppler-utils

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8013
ENTRYPOINT [ "python3", "run.py" ]
